# Generated by Django 3.0.7 on 2020-06-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['completed', '-updated', '-timestamp']},
        ),
    ]
